### ISSUE TITLE
Feature Request: return to previous note

### ISSUE THREAD

**Issue by blurm** [champloohq/tusk#12]
When browse note you might jump to another note from the note link. It's quite useful if there's shortcut to return to the previous one.

Or even better, we can mark notes in certain position, then return to it. 
Like in vim, you can set mark {a-zA-Z} at cursor position with ` m{a-zA-Z}`, and Jump to the mark {a-z} with '{a-z} or `{a-z}

**Comment by klauscfhq** [comment]
Added chrome-like `tab-switching` feature  on [`859ddea`](https://github.com/champloohq/tusk/commit/859ddeaa18181ca7fa41ff65fea8e82537738980), where the user can now switch between previews and next notes relative to the currently selected note, using `Ctrl/Cmd` + `Tab` and `Ctrl/Cmd` +`Shift` + `Tab`.
