### ISSUE TITLE
Feature request/improvement: Style Toggles  

### ISSUE THREAD

**Issue by xhaavardx** [champloohq/tusk#14]
# Style toggle is unintuitive 🚀
It is currently possible to toggle both Dark mode and Black mode at the same time. This makes for some really bad UX (user experience). In order to back to plain mode when both are toggled you have to reverse the steps, toggling black, then toggling dark, or opposite. It would be much easier if toggling one, while the other is toggled, reversed their values, so to speak. Else when toggling, return to white mode.

Kinda like this:
```

const toggleBlack = () => {

    if (!blackMode && !darkMode) {
        blackMode = true;
    } else if (!blackMode && darkMode) {
          darkMode = false;
          blackMode = true;
    } else {
          blackMode = false;
    }
};


// This was only for toggleBlack. It would also have to be done on dark mode, 
// and maybe sepia too, if it happens to behave the same way too. 

```
This is just an codified example of how I imagine it working. I hope it gets the point across.

**Comment by mariocfhq** [comment]
Dynamic memoryless theme traversing was added on [`b57febe`](https://github.com/champloohq/tusk/commit/b57febed823feb64b8be89d921815e3432a54cb8).
