### ISSUE TITLE
Feature Request: Better systray icon

### ISSUE THREAD

**Issue by mhalano** [champloohq/tusk#2]
## Description
Systray icon could have more options, like Settings, instead of just Toggle and Quit and should be optional.

## Environment
I'm running Ubuntu 16.04 with Tusk 0.1.0

**Comment by TimmyzBeach** [comment]
Additionally, there should be an option to disable the systray/menu bar icon so that it does not appear at all.

**Comment by klauscfhq** [comment]
A new featureful tray icon menu will be released on `v0.2.1`, bringing a lot of quickly accessible options for `Linux` and `Windows` users.
Thank you for dropping by and sharing your thoughts on this one! 
You are more than welcome to keep doing so : )
