### ISSUE TITLE
Font color in Dark Theme is too dark

### ISSUE THREAD

**Issue by gustavoaca1997** [champloohq/tusk#23]
# Font color in Dark and Black Themes is too dark
## Description
Unlike screenshots on README file the font color in _Dark Theme_ and in _Black Theme_ is gray, too dark, making it unreadable

## Environment

```OS Type: 	Linux
OS Platform:	linux
OS Release: 	4.4.0-96-generic
Architecture: 	x64
```
**Tusk version:** 0.5.1

**Comment by klauscfhq** [comment]
You can change the text color to any you like using the colors palette from the editor toolbar.

**Comment by jakeoung** [comment]
I have the same issue here. I want to make it readable without changing the color.
