### ISSUE TITLE
Hacktoberfest: Update Dependencies

### ISSUE THREAD

**Issue by klauscfhq** [champloohq/tusk#24]
Hello! : )
To celebrate the Hacktoberfest festivities, everyone is welcome to update the a following group of `dependencies` to their latest versions. It should be really simple and easy. Here are the links to the packages on `npmjs.com`, you can find their latest version on the right side of the page:

- [`ms`](https://www.npmjs.com/package/ms)
- [`fs-extra`](https://www.npmjs.com/package/fs-extra)
- [`simple-get`](https://www.npmjs.com/package/simple-get)
- [`time-stamp`](https://www.npmjs.com/package/time-stamp)

Happy Hacktoberfest and happy hacking! 🎉

**Comment by codebu5ter** [comment]
@klauscfhq Hi! Can I take this up? :)
