### ISSUE TITLE
Pdf file preview

### ISSUE THREAD

**Issue by leopenausa** [champloohq/tusk#26]
![screenshot from 2017-10-03 11-54-51](https://user-images.githubusercontent.com/4998227/31119641-e8daca22-a831-11e7-845e-17712ecc2b4c.png)

When adding a pdf file to a new note, by dragging and dropping the file on the note, the image inside the pdf file can be seen in the preview box from the note list, but not in the note itself.
It only appears a link that opens the pdf file in the web browser version of evernote.

If the image can be seen in the small note preview, why cannot it be displayed in the note itself? This is the default behaviour with image files (jpeg, png, etc), but not with pdfs.

I use tusk as an image repository to classify different topics, but working with pdf files is not easy with this behaviour.

**Comment by klauscfhq** [comment]
This is a default behavior engineered by Evernote itself and not by Tusk. If you would like it updated, you should probably address your thoughts at one of their [forums] (https://discussion.evernote.com). Thank you for dropping by and mentioning it : )
