### ISSUE TITLE
Support yinxiang(Evernote in China) account signin

### ISSUE THREAD

**Issue by blurm** [champloohq/tusk#3]
Hi,
Updated, the screenshot for offical login, the red circle part is the link for yinxiang account
![evenote_anno](https://user-images.githubusercontent.com/10203631/29950829-fa62a756-8ef0-11e7-8edd-35dc42fdafea.png)

Exellent app! Espencially the shortcut part!
Since Evernote has different account system and independent server in China, Tusk is unavailable for chinese users unfortunately
[www.yinxiang.com](url)
Any plan in future to support it?

**Comment by charon120** [comment]
可以登录，登录窗口左下角切换到印象笔记。

**Comment by blurm** [comment]
@charon120 我的系统是ubuntu16.04， tusk0.1.0，左下角什么都没有，登录选项都集中在页面中间
sign in with google
或者输入用户名密码登录，仅支持international account

**Comment by charon120** [comment]
不在大陆？
“继续"按钮下有一个选项
->切换到Evernote International
->切换到印象笔记

**Comment by blurm** [comment]
@charon120 之前是连了ssr，关掉之后还是一样的。我的“继续”下面只有“create account”

**Comment by bsed** [comment]
i have same problem

**Comment by klauscfhq** [comment]
Thank for taking the time to suggest the feature, it would really be super awesome to support it! 🎉 
Please correct me if I am wrong, this is the `login` link `https://app.yinxiang.com/Login.action` to the app, right? If so, it does not seam to be too hard to implement, a button or a menu option holding a redirect link to `https://app.yinxiang.com/Login.action` could be added, in order for the user to login.
We will definitely try testing it out and attempt to add it on the upcoming release. Please feel free to add anything new on this one : )

**Comment by blurm** [comment]
@klauscfhq Exactly. I updated the issue, added a screenshot. That is the offical login page, you can see there's a link which redirect to `https://app.yinxiang.com/Login.action` below `continue`for yinxiang account signin

**Comment by bsed** [comment]
After adding, this is really wonderful，very looking forward to the feature,

**Comment by bsed** [comment]
I went back in the evening and tried to download ！ @klauscfhq  thank you ，谢谢

**Comment by klauscfhq** [comment]
Added support for `Yinxiang` on [`db6d5d6`](https://github.com/champloohq/tusk/commit/db6d5d620b4c1dfc299418aa192a08495905dfa2). The release will be out really soon. Hope you enjoy it : )
