### ISSUE TITLE
Feature Request: option to "Zoom" out

### ISSUE THREAD

**Issue by myersg86** [champloohq/tusk#7]
Tusk is a truly great app and I absolutely love using it.
I can't tell you how long I've been hoping and waiting for someone to make a truly "native" feeling Evernote client that runs great on Linux. Thank you!

The one and only enhancement would be if you offer a way to "Zoom Out".
Before your app came along, I was using the regular web client for Evernote and I grew accustomed to having the zoom set to between **80% and 90%** of the 'normal' size. 
This gives me a much better "overview" when I'm sorting through hundreds of notes, and just seems to be more efficient for my workflow.

I am a Professional Web Developer and although I don't have much electron experience, I'm plenty comfortable with HTML/CSS/JS - if there is anything I can do to assist, please don't hesitate to ask.

**Comment by blurm** [comment]
`zoom in` and `zoom out` feature would be great feature, espencially on high DPI screen(4k,2k)

**Comment by klauscfhq** [comment]
Thank you so much for your kind words! Knowing that people enjoy the app is the best reward there is : )
Making the app's interface scalable, so it can better match each user's preferences, was a feature that we really wanted to implement as soon as possible. With [`3073baa`](https://github.com/champloohq/tusk/commit/3073baa46f897a49f978b19217c3ff987381169b) support for options to `Make Text Larger`, `Make Text Smaller` and `Reset Zoom Level` has been added.

Also, a new `Developing` section will be added on the project's `readme`, with info on how to quickly get started and contribute to the app's development. Everyone is super welcome 😄 

The release will be out really soon, hope you all enjoy it! 🎉 

Here is a small in-action preview 📷 

![2017-09-02_05-13-54](https://user-images.githubusercontent.com/12670537/29992824-f8425c2e-8fad-11e7-8a01-18e99929156d.gif)
